#spring.application.name=EmployeeAuthService
server.port = 8080

# MySQL DB Config
spring.datasource.url=jdbc:mysql://localhost:3306/new_schema
spring.datasource.username={Sample_UserName}
spring.datasource.password={Sample_Password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.application.name=employee-auth-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

